# Ultra-Fast Test - 最少配置验证pipeline
experiment:
  name: "ultrafast_paradox_test"
  description: "Ultra fast paradox test - 最少episodes验证"
  version: "1.0"

environment:
  id: "LunarLander-v3"
  success_threshold: 200
  
  noise_levels:
    noise_paradox_boundary_0.025: 0.025  # 只测试一个噪声水平
  
  active_noise_levels: ["noise_paradox_boundary_0.025"]

algorithms:
  active: ["bootstrapped_dqn"]
  
  configs:
    bootstrapped_dqn:
      type: "ensemble"
      uncertainty_type: "ensemble_std"
      n_heads: 10
      bootstrap_prob: 0.65
      uncertainty_estimation:
        method: "ensemble_std"
        bootstrap_samples: 50  # 减少bootstrap

data:
  n_seeds: 1              # 只用1个种子
  seeds: [101]            
  n_episodes_per_seed: 2  # 只要2个episodes!!
  eval_episodes: 2        # 总共2个episodes
  n_mc_samples: 5         # 最少MC采样
  bootstrap_samples: 20   # 最少bootstrap
  confidence_levels: [0.9]

metrics:
  distributional:
    crps:
      enabled: true
      variants: ["ensemble"]
  
  calibration:
    ace:
      enabled: true
      confidence_levels: [0.9]

calibration:
  enabled: true
  validation_split: 0.5   # 更大validation split，因为数据少

paths:
  base_dir: "uq_pipeline"
  data_dir: "uq_results/ultrafast_test"
  results_dir: "uq_results/ultrafast_test/results"
  models_dir: "logs/multi_env_experiments"
  cache_dir: ".cache"

model_load:
  device: "cpu"
  force_cpu: true
  custom_objects:
    learning_rate: 0.0
    lr_schedule: null
    exploration_schedule: null

execution:
  pipeline:
    skip_existing: false  # Force rerun
    cache_duration_hours: 0
    force_rerun: true
  
  stages:
    stage0_config: true
    stage1_dataset: true
    stage2_performance: true
    stage3_q_extraction: true
    stage4_metrics: true
    stage5_calibration: true
    stage6_report: false  # Skip buggy stage6
  
  error_handling:
    continue_on_failure: false
    retry_attempts: 1

logging:
  level: "INFO"
  console_enabled: true
  file_enabled: true
  log_file: "ultrafast_test.log"

global:
  seed: 42
  reproducible: true
  compression:
    enabled: true
    format: "xz"
    level: 1  # 最快压缩